import type { NextRequest } from "next/server"

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const city = searchParams.get("city") || "Thane"
  const type = searchParams.get("type") || "Government"
  const specialization = searchParams.get("specialization") || "General"

  // Simulate AI prediction delay
  await new Promise((resolve) => setTimeout(resolve, 1200))

  const predictions: Record<string, any> = {
    Thane: {
      predictedBeds: -19,
      topHospitals: [
        {
          rank: 34,
          name: "Jaigurudev Hospital",
          availableBeds: 347,
          totalBeds: 406,
          address: "Ghodbunder Road, Thane West",
          distance: "2.3 km",
          phone: "+91-22-2580-6000",
          type: "Private",
          doctorsOnDuty: 28,
          opdQueue: 12,
          bloodBank: { A: 45, B: 32, O: 58, AB: 18 },
          lastUpdated: "2:55:06 PM",
        },
        {
          rank: 40,
          name: "Super Speciality Hospital",
          availableBeds: 316,
          totalBeds: 332,
          address: "Pokhran Road No 2, Thane",
          distance: "3.1 km",
          phone: "+91-22-2534-7000",
          type: "Private",
          doctorsOnDuty: 22,
          opdQueue: 18,
          bloodBank: { A: 38, B: 28, O: 52, AB: 15 },
          lastUpdated: "2:54:32 PM",
        },
        {
          rank: 17,
          name: "Jag Pravesh Chandra Hospital",
          availableBeds: 277,
          totalBeds: 435,
          address: "Majiwada, Thane West",
          distance: "4.5 km",
          phone: "+91-22-2580-3000",
          type: "Government",
          doctorsOnDuty: 35,
          opdQueue: 24,
          bloodBank: { A: 52, B: 41, O: 68, AB: 22 },
          lastUpdated: "2:53:18 PM",
        },
        {
          rank: 33,
          name: "Max Super Speciality",
          availableBeds: 241,
          totalBeds: 325,
          address: "Manpada, Thane East",
          distance: "5.2 km",
          phone: "+91-22-6629-6000",
          type: "Private",
          doctorsOnDuty: 26,
          opdQueue: 15,
          bloodBank: { A: 42, B: 35, O: 61, AB: 19 },
          lastUpdated: "2:55:42 PM",
        },
        {
          rank: 96,
          name: "Bethany Hospital",
          availableBeds: 196,
          totalBeds: 478,
          address: "Naupada, Thane West",
          distance: "6.1 km",
          phone: "+91-22-2533-4000",
          type: "Trust",
          doctorsOnDuty: 38,
          opdQueue: 28,
          bloodBank: { A: 58, B: 46, O: 75, AB: 25 },
          lastUpdated: "2:52:55 PM",
        },
      ],
    },
    Delhi: {
      predictedBeds: 45,
      topHospitals: [
        {
          rank: 12,
          name: "AIIMS Delhi",
          availableBeds: 420,
          totalBeds: 500,
          address: "Ansari Nagar, New Delhi",
          distance: "5.2 km",
          phone: "+91-11-2658-8500",
          type: "Government",
          doctorsOnDuty: 65,
          opdQueue: 42,
          bloodBank: { A: 85, B: 72, O: 110, AB: 38 },
          lastUpdated: "2:54:15 PM",
        },
        {
          rank: 23,
          name: "Safdarjung Hospital",
          availableBeds: 380,
          totalBeds: 450,
          address: "Ring Road, New Delhi",
          distance: "7.8 km",
          phone: "+91-11-2673-0000",
          type: "Government",
          doctorsOnDuty: 58,
          opdQueue: 38,
          bloodBank: { A: 78, B: 65, O: 98, AB: 32 },
          lastUpdated: "2:53:48 PM",
        },
        {
          rank: 34,
          name: "Ram Manohar Lohia",
          availableBeds: 310,
          totalBeds: 400,
          address: "Baba Kharak Singh Marg",
          distance: "8.5 km",
          phone: "+91-11-2336-5525",
          type: "Government",
          doctorsOnDuty: 48,
          opdQueue: 32,
          bloodBank: { A: 65, B: 55, O: 88, AB: 28 },
          lastUpdated: "2:55:22 PM",
        },
        {
          rank: 45,
          name: "GTB Hospital",
          availableBeds: 280,
          totalBeds: 380,
          address: "Dilshad Garden, Delhi",
          distance: "12.3 km",
          phone: "+91-11-2232-3232",
          type: "Government",
          doctorsOnDuty: 42,
          opdQueue: 28,
          bloodBank: { A: 58, B: 48, O: 78, AB: 24 },
          lastUpdated: "2:52:38 PM",
        },
        {
          rank: 56,
          name: "Lok Nayak Hospital",
          availableBeds: 250,
          totalBeds: 350,
          address: "Jawaharlal Nehru Marg",
          distance: "9.1 km",
          phone: "+91-11-2323-4242",
          type: "Government",
          doctorsOnDuty: 38,
          opdQueue: 25,
          bloodBank: { A: 52, B: 42, O: 72, AB: 22 },
          lastUpdated: "2:54:58 PM",
        },
      ],
    },
    Mumbai: {
      predictedBeds: 32,
      topHospitals: [
        {
          rank: 8,
          name: "KEM Hospital",
          availableBeds: 390,
          totalBeds: 480,
          address: "Parel, Mumbai",
          distance: "3.5 km",
          phone: "+91-22-2410-7000",
          type: "Government",
          doctorsOnDuty: 62,
          opdQueue: 45,
          bloodBank: { A: 82, B: 68, O: 105, AB: 35 },
          lastUpdated: "2:53:12 PM",
        },
        {
          rank: 15,
          name: "Sion Hospital",
          availableBeds: 350,
          totalBeds: 420,
          address: "Sion, Mumbai",
          distance: "4.2 km",
          phone: "+91-22-2407-6301",
          type: "Government",
          doctorsOnDuty: 55,
          opdQueue: 38,
          bloodBank: { A: 72, B: 62, O: 95, AB: 32 },
          lastUpdated: "2:54:45 PM",
        },
        {
          rank: 22,
          name: "Nair Hospital",
          availableBeds: 320,
          totalBeds: 400,
          address: "Mumbai Central",
          distance: "5.8 km",
          phone: "+91-22-2302-7643",
          type: "Government",
          doctorsOnDuty: 48,
          opdQueue: 32,
          bloodBank: { A: 65, B: 55, O: 85, AB: 28 },
          lastUpdated: "2:52:28 PM",
        },
        {
          rank: 31,
          name: "JJ Hospital",
          availableBeds: 290,
          totalBeds: 370,
          address: "Byculla, Mumbai",
          distance: "6.5 km",
          phone: "+91-22-2373-5555",
          type: "Government",
          doctorsOnDuty: 42,
          opdQueue: 28,
          bloodBank: { A: 58, B: 48, O: 78, AB: 25 },
          lastUpdated: "2:55:18 PM",
        },
        {
          rank: 42,
          name: "Rajawadi Hospital",
          availableBeds: 260,
          totalBeds: 340,
          address: "Ghatkopar, Mumbai",
          distance: "11.2 km",
          phone: "+91-22-2510-0503",
          type: "Government",
          doctorsOnDuty: 38,
          opdQueue: 24,
          bloodBank: { A: 52, B: 42, O: 68, AB: 22 },
          lastUpdated: "2:53:52 PM",
        },
      ],
    },
  }

  const result = predictions[city] || predictions.Thane

  return Response.json(result)
}
